### ISSUE TITLE
inTouch app dead ?

### ISSUE THREAD

**Issue by MiG-41** [jonkristian/alko#5]
Are inTouch servers have some issues ?
Since more then one week my Robolinho is not visible in app. I made a reset inTouch from Robolinho menu , conected once again to wifi , removed from inTouch ap , and it can't connect any more.
I can see , that Robolinho is connecting to Wifi every 2 min. ( and pobably is not able to o something in server , and it do reset after 2 min).  Internet is availble from this network , but not works.
I send a mail to Al-Ko support last friday , but till now they answer was a question :" From where  am  I ? " and no further responce....

**Comment by Whomeyes** [comment]
Yes its dead, add your mail here to get updates.
https://alko-garden.se/drift

**Comment by MiG-41** [comment]
Just to remind , my Robolinho went to service for WiFi module exchange , update was not completed , so it  was somehow locked.
Now app works again. Hope also integration can work again for next season...
